### PR TITLE
Fixed bug with multiple paths in mount

### PR DESCRIPTION
**Pull request by kozl**
Fixes concatenating multiple paths in mount. Described in Issue #29

### CODE REVIEW

**Comment by RosscoeP** [comment]
I too had this issue.
my hiera was:-
      mounts:
        sandpit:
          - function/%{function}
          - job/%{job}
          - climate/%{climate}
          - product/%{product}
          - role/%{role}
          - stack/%{stack}
          - platform/%{platform}
          - common
I "fixed" it in a local copy of the hiera_vault.rb code (version 0.3.0).
:129
-     kv_mounts = options['mounts'].dup
+    store = options['mounts'].keys[0]
+    kv_mounts = options['mounts'][store].dup

:136
-     path = context.interpolate(File.join(mount, key))
+     path = context.interpolate(File.join(store, mount, key))

**Comment by kozl** [comment]
@petems Could you review and merge?

**Comment by petems** [comment]
@kozl Can you fix the conflicts, then I'll merge 👍

**Comment by kozl** [comment]
done

**Comment by petems** [comment]
Nice, thanks. Let me just fix travis, when it's green I'll merge 👍

**Pull request merged**
