### PR TITLE
v1 candidate

### PR DESCRIPTION
**Pull request by traviscosgrave**
This PR is closer to a request for comment.

I was unable on my host to get the specs running, and as such did not add any (although the approach should allow all of the functionality to exist. Also, these changes require the changes I added to the hiera-vault gem to support real LIST requests https://github.com/hashicorp/vault-ruby/pull/201.

The function has been re-written such that it behaves more like the other standard hiera back ends, running the function once per uri passed in. It takes advantage of the global vault client, but reconfigures it before each lookup to ensure environment caching doesn't cause any problems. Configuration is cached for each path, and the keys found at each path and any values returned are cache to reduce the calls to vault and provide as static a view on the secret set as possible.

There is a construct for adding other backends, and supporting interleaved backends is now possible as the configuration for the mount and the list of paths are handled separately.

A pattern for handling environment specific field values (eg for testing a new version of a secret before rolling it out infra wide) also has been developed with the `environment_delimiter` option.

### CODE REVIEW

**Comment by petems** [comment]
@traviscosgrave This looks great! The main issue is that I dont really want to merge this until the features are added into the core gem...

Let me check on the status of that and see if I can get that merged

**Comment by traviscosgrave** [comment]
Of course! We're running both forks locally, and I'm not sure my patch to the core gem is the _best_ way to solve the problem of the HTTP client on supporting the `LIST` method. Gotta keep moving though.

Also, this is now up-to-date with our current implementation. I ran into some issues with cached environments and JRubies either garbage collecting or nodes in a weird state (migrating from one cluster to another) hitting the error and the global $vault being blown away. The most recent change removes the forced nil on the $vault client and will recreate one if it get's GC'd. Thanks for following up

**Comment by fduranti** [comment]
Any news on this? 
The hiera fallback is something that I'll really like to have :)

**Comment by traviscosgrave** [comment]
I'm still battling the error mentioned above, I hope to have some kind of solution this week and I'll update the PR accordingly.

**Comment by traviscosgrave** [comment]
Using the retry feature of the vault client I was able to resolve the race condition whereby a pool is shutting down mid-request especially in cached environments. I've also eliminated the need for the weird support of the LIST http method by instead upgrading the local vault agent to the latest 1.1.3 (in which a bug preventing query string parameters from being proxied was fixed).

This is now looking good in our environment. Looking forward to the comments.

Asside: I did attempt to use the built in Puppet::HttpPool, but it required some nasty tricks and was about 50% slower on catalogs with many lookups even after forcing it to reuse connections.

**Comment by fduranti** [comment]
@traviscosgrave You still need https://github.com/hashicorp/vault-ruby/pull/201 before merging this ?

**Comment by traviscosgrave** [comment]
hashicorp/vault-ruby#201 is _only_ required if you plan to use vault agent before version 1.1.3. It shouldn't be required if you talk directly from your puppet server/agent to vault. (Although that case is currently outside our scope due to a strict vault cipher set that is unsupported by the jruby net:http implementeation). [The current code is what we have have running now.]

**Comment by petems** [comment]
@traviscosgrave Can you resolve the conflict then I can merge? 👍

**Comment by traviscosgrave** [comment]
I'll see what I can do, there's a lot that I moved around.

**Comment by petems** [comment]
I've merged https://github.com/petems/petems-hiera_vault/pull/41 in the mean time, which doesnt seem to require changes to the gem, can you test this works for you now?

**Comment by AndreasDilworth** [comment]
I tried #41- and it is broken for v2 stores (and actually doesn't work well for v1 either).
This PR works very well (really good job, @traviscosgrave!) and I do hope this gets merged! As mentioned, it does not require hashicorp/vault-ruby#201 as long as an updated Vault-agent is used.

I just have two nitpicks:
- The continue_if_not_found option should be documented and/or should be true by default as Hiera will otherwise stop making further lookups if no value is found on first URI - which might not be expected behaviour.
- The environment_delimiter option could be made optional as some might prefer separating environments by URI instead.

**Pull request closed without merging**
