### PR TITLE
WIP: Fetch Vault token from file

### PR DESCRIPTION
**Pull request by jovandeginste**
In our setup, we have multiple Vault locations to read from. Some are even on different Vault clusters (QA Vault for QA servers). They all go through the same Puppet master. For this reason, we added a `tokenfile` option, which contains the Vault token for that particular hiera scope. Eg, inside module "Mymodule":

```yaml
hierarchy:
  - name: "Hiera-vault lookup Mymodule P"
    lookup_key: hiera_vault
    options:
      confine_to_keys:
        - "^mymodule::vaultp::.*"
      strip_from_keys:
        - "^mymodule::vaultp::"
      ssl_verify: true
      address: https://vault-p.example.org
      default_field: value
      default_field_parse: json
      mounts:
        generic:
          - secret/projects/icts-p-mymodule
  - name: "Hiera-vault lookup Mymodule Q"
    lookup_key: hiera_vault
    options:
      confine_to_keys:
        - "^mymodule::vaultq::.*"
      strip_from_keys:
        - "^mymodule::vaultq::"
      ssl_verify: true
      address: https://vault-q.example.org
      tokenfile: /opt/puppetlabs/server/data/puppetserver/.vault-token-q
      default_field: value
      default_field_parse: json
      mounts:
        generic:
          - secret/projects/icts-q-mymodule
```

The configuration for P used the default token in the environment, while the configuration for Q uses the token found in `/opt/puppetlabs/server/data/puppetserver/.vault-token-q`.

### CODE REVIEW

**Comment by petems** [comment]
Looks like there's a conflict here, can you rebase?

**Comment by jovandeginste** [comment]
I can, just wanted to know if you're interested in this first. This change is a few years old already in our fork...

**Comment by petems** [comment]
Wait, I'm just re-reading this over now... you can currently reference a token from a file by giving it as a path to the token config entry, it's in the docs:

> token: The token to authenticate with Vault, also read as ENV["VAULT_TOKEN"] or a full path to the file with the token (eg. /etc/vault_token.txt). When bootstrapping, you can set this token as IGNORE-VAULT and the backend will be stubbed, which can be useful when bootstrapping.

Is there a reason you want it as a specific configuration setting as tokenfile?

**Comment by jovandeginste** [comment]
Does this support different Vault tokens, eg. when used with different Vault servers (in the same `hiera.yaml`)? My example fetches secrets from different scopes with different credentials... (I hope my explanation is somewhat clear)

**Comment by petems** [comment]
As far as I know yes, each chunk of config can have its own token, scope, paths etc.

**Comment by jovandeginste** [comment]
Just checked [the code](https://github.com/petems/petems-hiera_vault/blob/master/lib/puppet/functions/hiera_vault.rb#L92), I believe you are right! This was not available when I started using this module. I will check if this obsoletes my PR. I'll put the PR as WIP for now.

**Comment by petems** [comment]
No worries, always glad to help people using projects I'm maintaining 😄

**Pull request closed without merging**
