### PR TITLE
Adds v2 fix for `default_field`

### PR DESCRIPTION
**Pull request by petems**
* New code assumed user using ‘value’
* Added new specs for v2 mount
* Bumped Vault gem version to 0.13.0

### CODE REVIEW

**Comment by petems** [comment]
@maxadamo and @arcenik Hello!

Can you both check this branch in your environments? The previous code seemed to have one issue where you want to use a different field than `value`, as well as not setting one by default. So I added that logic and changed it to branching over rescuing the code.

**Comment by maxadamo** [comment]
note taken @petems .... will do ...

**Comment by arcenik** [comment]
That works for me.

**Comment by maxadamo** [comment]
works for me too

**Pull request merged**
