### PR TITLE
Fix kv2 support

### PR DESCRIPTION
**Pull request by maxadamo**
This is a PR on top of PR https://github.com/petems/petems-hiera_vault/pull/41

### CODE REVIEW

**Comment by maxadamo** [comment]
with this last commit it's compliant with the was you have used the key names on v1 (having `value` as the name of the key). @petems how does this look to you?

**Comment by petems** [comment]
This looks good to me! Give me a chance to quickly test it and then I'll merge

I need to get a proper acceptance test setup for this as well, right now it's all pretty manual!

**Comment by arcenik** [comment]
Hi, this does not work on my setup, as it causes a crash on the server.

The versions are:
* foreman-release-1.23.1-1.el7.noarch
* puppet6-release-6.0.0-5.el7.noarch
* puppet-agent-6.11.1-1.el7.x86_64
* puppetserver-6.7.2-1.el7.noarch

My hiera config is as follow:

```
hierarchy:
  - name: "Vault Lookup"
    lookup_key: hiera_vault
    options:
      confine_to_keys:
      - '^.*_password$'
      - '^.*_user$'

      ssl_verify: true
      address: https://my-vault:8200/

      token: /etc/puppetlabs/puppet/vault.token
      default_field: value

      mounts:
         hosting:
         - 'nodes/%{trusted.certname}'
         - 'customers/%{gce.project.projectId}'
         - 'customers/common'
```

The tests secret engines (with test secrets)

```
kv1 hosting/nodes/node0.project.internal/ -> [xxx1_password]
kv2 hosting/customers/my-project/         -> []
kv2 hosting/customers/common/             -> [xxx1_password,xxx2_password,xxx3_password]
```

This causes an error on the server 

```
2019-11-28T08:47:49.495Z ERROR [qtp1909530006-45] [puppetserver] Puppet Server Error: Evaluation Error: Error while evaluating a Resource Statement, Function lookup() did not find a value for the name 'xxx2_password' on node node0.project.internal
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/pops/lookup.rb:87:in `fail_lookup'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/pops/lookup.rb:57:in `lookup'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/functions/lookup.rb:210:in `do_lookup'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/functions/lookup.rb:202:in `lookup_4'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/pops/functions/dispatch.rb:60:in `invoke'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/pops/functions/dispatcher.rb:43:in `block in dispatch'
org/jruby/RubyKernel.java:1193:in `catch'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/pops/functions/dispatcher.rb:42:in `dispatch'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/pops/functions/function.rb:46:in `block in call'
org/jruby/RubyKernel.java:1193:in `catch'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/pops/functions/function.rb:45:in `call'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/pops/puppet_stack.rb:42:in `stack'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/pops/evaluator/runtime3_support.rb:305:in `block in call_function'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util/profiler/around_profiler.rb:58:in `profile'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util/profiler.rb:51:in `profile'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/pops/evaluator/runtime3_support.rb:303:in `call_function'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/pops/evaluator/evaluator_impl.rb:976:in `call_function_with_block'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/pops/evaluator/evaluator_impl.rb:945:in `eval_CallNamedFunctionExpression'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/pops/visitor.rb:94:in `visit_this_1'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/pops/evaluator/evaluator_impl.rb:81:in `evaluate'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/pops/evaluator/evaluator_impl.rb:370:in `eval_AssignmentExpression'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/pops/visitor.rb:94:in `visit_this_1'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/pops/evaluator/evaluator_impl.rb:81:in `evaluate'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/pops/evaluator/evaluator_impl.rb:660:in `block in eval_BlockExpression'
org/jruby/RubyArray.java:1800:in `each'
org/jruby/RubyEnumerable.java:1093:in `inject'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/pops/evaluator/evaluator_impl.rb:660:in `eval_BlockExpression'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/pops/visitor.rb:94:in `visit_this_1'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/pops/evaluator/evaluator_impl.rb:81:in `evaluate'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/pops/parser/evaluating_parser.rb:63:in `evaluate'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/parser/ast/pops_bridge.rb:32:in `evaluate'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/parser/ast/pops_bridge.rb:72:in `block in evaluate'
org/jruby/RubyKernel.java:1193:in `catch'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/parser/ast/pops_bridge.rb:71:in `block in evaluate'
org/jruby/RubyKernel.java:1193:in `catch'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/parser/ast/pops_bridge.rb:70:in `evaluate'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/parser/ast.rb:30:in `safeevaluate'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/resource/type.rb:137:in `evaluate_code'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/parser/resource.rb:79:in `block in evaluate'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util/profiler/around_profiler.rb:58:in `profile'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util/profiler.rb:51:in `profile'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/parser/resource.rb:71:in `evaluate'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/parser/compiler.rb:541:in `block in evaluate_definitions'
org/jruby/RubyArray.java:1800:in `each'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/parser/compiler.rb:539:in `block in evaluate_definitions'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util/profiler/around_profiler.rb:58:in `profile'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util/profiler.rb:51:in `profile'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/parser/compiler.rb:538:in `block in evaluate_definitions'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util/errors.rb:115:in `exceptwrap'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/parser/compiler.rb:537:in `evaluate_definitions'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/parser/compiler.rb:570:in `block in evaluate_generators'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util/profiler/around_profiler.rb:58:in `profile'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util/profiler.rb:51:in `profile'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/parser/compiler.rb:567:in `block in evaluate_generators'
org/jruby/RubyKernel.java:1425:in `loop'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/parser/compiler.rb:564:in `evaluate_generators'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/parser/compiler.rb:179:in `block in compile'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util/profiler/around_profiler.rb:58:in `profile'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util/profiler.rb:51:in `profile'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/parser/compiler.rb:179:in `block in compile'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/context.rb:62:in `override'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet.rb:274:in `override'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/parser/compiler.rb:155:in `compile'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/parser/compiler.rb:34:in `compile'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/indirector/catalog/compiler.rb:307:in `block in compile'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util/profiler/around_profiler.rb:58:in `profile'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util/profiler.rb:51:in `profile'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/indirector/catalog/compiler.rb:305:in `block in compile'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util.rb:233:in `block in benchmark'
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/benchmark.rb:308:in `realtime'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util.rb:232:in `benchmark'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/indirector/catalog/compiler.rb:303:in `compile'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/indirector/catalog/compiler.rb:56:in `block in find'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/node/environment.rb:423:in `with_text_domain'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/indirector/catalog/compiler.rb:55:in `find'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/indirector/indirection.rb:223:in `find'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/network/http/api/indirected_routes.rb:138:in `do_find'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/network/http/api/indirected_routes.rb:54:in `block in call'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/context.rb:62:in `override'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet.rb:274:in `override'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/network/http/api/indirected_routes.rb:53:in `call'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/network/http/route.rb:82:in `block in process'
org/jruby/RubyArray.java:1800:in `each'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/network/http/route.rb:81:in `process'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/network/http/route.rb:88:in `process'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/network/http/route.rb:88:in `process'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/network/http/handler.rb:87:in `block in process'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/network/http/handler.rb:70:in `block in with_request_profiling'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util/profiler/around_profiler.rb:58:in `profile'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util/profiler.rb:51:in `profile'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/network/http/handler.rb:66:in `with_request_profiling'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/network/http/handler.rb:86:in `block in process'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/network/http/handler.rb:93:in `respond_to_errors'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/network/http/handler.rb:85:in `process'
uri:classloader:/puppetserver-lib/puppet/server/master.rb:52:in `block in handleRequest'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/context.rb:62:in `override'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet.rb:274:in `override'
uri:classloader:/puppetserver-lib/puppet/server/master.rb:51:in `handleRequest'
```

**Comment by maxadamo** [comment]
@arcenik thanks for testing it. I have it in production already and I have the same versions as you (apart from foreman, which I don't have). Even the hiera stanza for vault is about the same and I have observed your same error in the puppetserver logs, **only** when I was running a lookup without `Optional` and the variable was not found. 
For instance this one was failing:
 ```
$sudo_group = lookup('base_os::linux::sudo::group'),
```
this was succeeds:
```
$sudo_group = lookup('base_os::linux::sudo::group', Optional[Array], 'unique', []),
```

Are you running `puppet lookup` or this is something you get from you puppet server logs? 
In the second case, I tend to believe that it may not be related to hiera_vaul.

**Comment by maxadamo** [comment]
@arcenik it's not related to hiera_vault and I fixed it by using Optional.  
This is your error:
```
2019-11-28T08:47:49.495Z ERROR [qtp1909530006-45] [puppetserver] Puppet Server Error: Evaluation Error: Error while evaluating a Resource Statement, Function lookup() did not find a value for the name 'xxx2_password' on node node0.project.internal
```
this is my error:
```
2019-11-28T06:04:44.218Z ERROR [qtp1115016060-151948] [puppetserver] Puppet Server Error: Function lookup() did not find a value for the name 'base_os::linux::sudo::group' (file: /etc/puppetlabs/code/environments/uat/modules/role/manifests/datawarehouse.pp, line: 28) on node uat-dwarehouse02.xxxxxx.org
```

**Comment by arcenik** [comment]
Hi,

Using a default value prevent the crash, but it is supposed to return the vault value from the third mount point and not the default one.

Best regards.

**Comment by maxadamo** [comment]
hi @arcenik ,

do you have the PuppetDB? If the answer is yes, can you run this command on your puppet server? 
```
puppet lookup xxx1_password --explain --node=node0.project.internal
```
and
```
puppet lookup xxx2_password --explain --node=node0.project.internal
```
p.s.: perhaps, you need the parameter `--compile`, because the puppet server defaults to `production` environment:
```
  puppet lookup xxx2_password --explain --compile.... blahblah
```

**Comment by arcenik** [comment]
Hi,

The *puppet lookup --explain* does not show any difference between my PR and your proposal.

To test, I'm using the following code (with one lookup commented):
```
$xxx2      = lookup('xxx2_password')
$xxx2      = lookup('xxx2_password', undef, undef, 'default2')
notify { "XXXXXXXXXXXXXXXXXXXXXX 2 : ${xxx2}": }
```

The result, using my merged PR, show *common2* from Vault *hosting/common* secret engine:
```
Info: Retrieving locales
Info: Loading facts
Info: Caching catalog for node0.project.internal
Info: Applying configuration version '6e478f97d158a5dc29d298ca6f02b7716089244a'
Notice: XXXXXXXXXXXXXXXXXXXXXX 2 : common2
Notice: /Stage[main]/Roles::Xxxtest/Notify[XXXXXXXXXXXXXXXXXXXXXX 2 : common2]/message: defined 'message' as 'XXXXXXXXXXXXXXXXXXXXXX 2 : common2'
Notice: Applied catalog in 4.30 seconds
```

Using your PR, it crash if no default value is given:
```
Info: Retrieving locales
Info: Loading facts
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Function lookup() did not find a value for the name 'xxx2_password' on node node0.project.internal
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run
```

Using your PR, it return the default value:
```
Info: Using configured environment 'dev'
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Retrieving locales
Info: Loading facts
Info: Caching catalog for node0.project.internal
Info: Applying configuration version '6e478f97d158a5dc29d298ca6f02b7716089244a'
Notice: XXXXXXXXXXXXXXXXXXXXXX 2 : default2
Notice: /Stage[main]/Roles::Xxxtest/Notify[XXXXXXXXXXXXXXXXXXXXXX 2 : default2]/message: defined 'message' as 'XXXXXXXXXXXXXXXXXXXXXX 2 : default2'
Notice: Applied catalog in 4.19 seconds
```

**Comment by arcenik** [comment]
I've found the problem with your PR on my setup: on kv2, you're inserting the 'data' item in the middle of the secret-engine name. therefore it cannot work.

On the vault audit logs I see
```
"hosting/nodes/node0.project.internal/xxx2_password"
"hosting/data/nodes/node0.project.internal/xxx2_password"
"hosting/customers/project/xxx2_password"
"hosting/data/customers/project/xxx2_password"
"hosting/customers/common/xxx2_password"
"hosting/data/customers/common/xxx2_password"
```

Instead of
```
"hosting/nodes/node0.project.internal/xxx2_password"
"hosting/nodes/node0.project.internal/data/xxx2_password"
"hosting/customers/project/xxx2_password"
"hosting/customers/project/data/xxx2_password"
"hosting/customers/common/xxx2_password"
"hosting/customers/common/data/xxx2_password"
```

On the Vault UI it looks like this

image

**Comment by maxadamo** [comment]
It's absolutely easy to switch from one configuration to the other, by simply changing this: 
```
v2_path = File.join(mount, 'data', path, key).chomp('/')
```
to this:
```
v2_path = File.join(mount, path, 'data', key).chomp('/')
```

For the sake of completeness, I am running: `Vault v1.3.0`

**Now we need to understand why it works for you in one way, and it works for me the way around.** 

Below is my sample key:
immagine

**Comment by maxadamo** [comment]
@arcenik here we go. 
If you open this URL: `https://learn.hashicorp.com/vault/secrets-management/sm-versioned-kv#step-1-check-the-kv-secrets-engine-version` (then scroll a little bit down, until **API call using cURL**), you'll see this example, which is the same one I am using: 

immagine

**Comment by arcenik** [comment]
So you are using one secret engine with one secret per customer/project/node and multiple keys/value.
While I'm using one secret engine per customer/project/node with multiple secrets and one key "value".

Can you implement your use case without breaking mine ?

Can you share your hiera configuration so I can see the differences ?

Thanks.

**Comment by maxadamo** [comment]
the relevant part of hiera is the following (and it's same a KV v1, apart from `confine_to_keys`):
```
- name: "Hiera Vault V2 Lookup"
  lookup_key: hiera_vault
  options:
    confine_to_keys:
      - '^vaultv2_.*'
    ssl_verify: false
    address: https://master.vault.consul.blahblah:8200
    token: xxxxxxxxxxxxxxxxxxxxxxx
    default_field: value
    mounts:
      puppet_v2:
        - "%{trusted.certname}"
        - "%{trusted.domain}"
        - "common"
```
p.s.: on a side, and completely unrelated note, I made a PR to [puppet-hiera](https://github.com/voxpupuli/puppet-hiera), version 4.0.0 is out and you can set file mode to 640 and put the token inside `hiera.yaml`

**Comment by maxadamo** [comment]
How do you see this solution? Is it elegant, looks bad? 
```ruby
  def get_kv_v2(mount, path, key)
    # we can have 'data' either before or after the path
    v2_path_one = File.join(mount, 'data', path, key).chomp('/')
    v2_path_two = File.join(mount, path, 'data', key).chomp('/')
    begin
      res = $vault.logical.read(v2_path_one).data[:data][:value]
    rescue
      begin
        res = $vault.logical.read(v2_path_two).data[:data][:value]
      rescue
        return $vault.logical.read(v2_path_two)
      end
    end
    return { :value => res }
  end
```

**Comment by arcenik** [comment]
How about this one ?
I think it is better to try the more specific first (a secret-engine with a longer name).

```ruby
  def get_kv_v2(mount, path, key)
    begin
      # secretengine -> mount+path / secret -> key / key -> default_field
      secretpath = File.join(mount, path, 'data', key).chomp('/')
      res = $vault.logical.read(secretpath).data[:data][:value]
    rescue
      begin
        # secretengine -> mount / secret -> path / key -> key
        secretpath = File.join(mount, 'data', path, key).chomp('/')
        res = $vault.logical.read(secretpath).data[:data][:value]
      rescue
        return { :value => res }
      end
    end
    return $vault.logical.read(secretpath)
  end
```

**Comment by maxadamo** [comment]
ahah! I saw you: you have put your path first :smile: 
That's ok, ultimately is your solution ... I'll try to add this one and then squash all the commits.

**Comment by arcenik** [comment]
I'll test it tomorrow.
You could also replace the comment by explain statements, giving explicitly the secret-engine name and the secret name being acceded.

**Comment by maxadamo** [comment]
I pushed the new commit (not squashed yet). 

Out of curiosity, secret engines are less flexible compared to secrets folders. For instance, they cannot be deleted, but only disabled, and you cannot create a new secret engine with the same name. 
If you have thousand nodes, are you sure that this is the way to go?

**Comment by arcenik** [comment]
The last commit is working for me.

About the secret engine flexibility, the Hashicorp documentation say the opposite :

**Comment by maxadamo** [comment]
@petems will you have time to test and merge this? It is working for us. 
On another note, since you are at Hashicorp, maybe you know thing that humans don't guess even :smile:  Are you aware of any best practice on secrets engine usage? Better using folders within the same secret engines or multiple secrets engines? Do hundred of secret engines risk to over-bloat Vault?

**Comment by petems** [comment]
@maxadamo We generally recommend separate concerns with secret engines, as it allows more granular RBAC and general control.

**Pull request merged**
